messManagementSystem/messManagementSystem/Controllers/DailyMessController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using messManagementSystem.messContext;
using messManagementSystem.Models;

namespace messManagementSystem.Controllers
{
    public class DailyMessController : Controller
    {
        MessCustContext _ds = new MessCustContext();
        //
        // GET: /DailyMess/

        public ActionResult Index(long custId)
        {
            ViewBag.custId = custId;

            var dailyMess = _ds.Dailymess.Where(s => s.custId.Equals(custId) && s.status == (byte)Status.Active);   

            return View(dailyMess);
        }


        public ActionResult Create(long id)
        {
            ViewBag.custId = id;

            DailyMess map = new DailyMess();

            ViewBag.CustomerCollection = _ds.GetCustomers().Where(c => c.status == (byte)Status.Active);

            return View(map);

        }

        [HttpPost]

        public ActionResult Create(DailyMess dailymess)
        {

            
          //  int IsAdded = 0;
            if (ModelState.IsValid)
            {
                //var daily = _ds.GetDailyMesss()
                //    .Where(PS => PS.custId.Equals(dailymess.custId)
                //        && PS.status == (byte)Status.Active);

                dailymess.lastUpdateDate = DateTime.UtcNow;
                dailymess.status = (byte)Status.Active;
                dailymess.lunchDateTime = DateTime.UtcNow;
                     
                _ds.CreateDailyMess(dailymess);  
            }
            ViewBag.CustomerCollection = _ds.GetCustomers().Where(c => c.status == (byte)Status.Active);
            ViewBag.custId = dailymess.custId;

            return View(dailymess);
        }
    }
}

messManagementSystem/messManagementSystem/Views/DailyMess/Create.cshtml
@model messManagementSystem.Models.DailyMess

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Food Searve by Customer on Daily Basis</legend>

        <div class="editor-label">
          CustId
        </div>
         <div class="editor-field">
            @Html.DropDownListFor(model => model.custId, new SelectList(ViewBag.CustomerCollection, "custId","custId"))
            <br />
            @Html.ValidationMessageFor(model => model.custId)
        </div>

        <div class="editor-label">
           CustomerName
        </div>
         <div class="editor-field">
            @Html.DropDownListFor(model => model.custMessName, new SelectList(ViewBag.CustomerCollection, "custFirstName", "custFirstName"))
            <br />
            @Html.ValidationMessageFor(model => model.custMessName)
        </div>
       @* <div class="editor-label">
            @Html.LabelFor(model => model.lunchDateTime)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.lunchDateTime)
            @Html.ValidationMessageFor(model => model.lunchDateTime)
        </div>*@

       @* <div class="editor-label">
            @Html.LabelFor(model => model.status)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.status)
            @Html.ValidationMessageFor(model => model.status)
        </div>*@

     @*   <div class="editor-label">
            @Html.LabelFor(model => model.lastUpdateDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.lastUpdateDate)
            @Html.ValidationMessageFor(model => model.lastUpdateDate)
        </div>*@

        <br />
        <p>
            <input type="submit" class="btn btn-primary btn-sm" value="Create" />  &nbsp &nbsp &nbsp &nbsp <input type="button" class="btn btn-primary btn-sm" value="Go Back" onclick="goBack()" />
        </p>
    </fieldset>
}

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script>  

    function goBack()
    { 
        window.location.href = '@Url.Action("Index","DailyMess", new { custId=@ViewBag.custId })';
    }
</script>

messManagementSystem/messManagementSystem/Views/DailyMess/Index.cshtml
@model IEnumerable<messManagementSystem.Models.DailyMess>

@{
    ViewBag.Title = "Index";
}

<h2>Daily Mess</h2>

<div class="pull-right">

    <input type="button" class="btn btn-primary btn-sm" value=" Add DailyMess" onclick="createDailymess()" /> 
</div> 
<br />
<br />
<table class="table">
    <tr style="background:#222222;">
        <th>
           SrNo
        </th>
        <th>
            CustName
        </th>
        <th>
            LunchTime
        </th>
        <th>
            Status
        </th> 
        <th> Actions</th>
    </tr>
    @{int index = 0;}
@foreach (var item in Model) {
    index = index + 1;
    <tr>
        <td><text>@index</text></td> 
        <td>
            @Html.DisplayFor(modelItem => item.custMessName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.lunchDateTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td> 
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.dailyMessID }) |
            @Html.ActionLink("Details", "Details", new { id=item.dailyMessID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.dailyMessID })
        </td>
    </tr>
}

</table>

<script>

    function createDailymess()
    {
        window.location.href = '@Url.Action("Create","DailyMess", new { id=@ViewBag.custId })'; 
         
    }

</script>